[package]
name = "clui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1", features = ["cargo"]}
eframe = "0.17"
shh = "1.0"
crossbeam-channel = "0.5.2"
